### ISSUE TITLE
Fix for phone without physical buttons

### ISSUE THREAD

**Issue by lucas-monteiro** [fagundes/cordova-plugin-navigationbar#1]
[NavigationBar.java.zip](https://github.com/fagundes/cordova-plugin-navigationbar/files/3095086/NavigationBar.java.zip)

Hello,
thank you for the shared repository.
I would like to propose an amendment. I know that the repository already has a lot of time, but in the phones that do not have physical button we have problems.

I would like to propose changes in lines 173 and 174 of the NavigationBar.java file:

window.clearFlags (0x04000000); // SDK 19: WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
                window.addFlags (0x80000000); // SDK 21: WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);

to

window.getDecorView (). setSystemUiVisibility (0x80000000 | 0x00000010); // FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS | SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR

Thanks

**Comment by fagundes** [comment]
OK. #3 merged.

**Comment by lucas-monteiro** [comment]
Muito obrigado!
