### ISSUE TITLE
"NavigationBarLigth"

### ISSUE THREAD

**Issue by nijakobius** [fagundes/cordova-plugin-navigationbar#12]
The docs have the following preference:

`<preference name="NavigationBarLigth" value="true" />`

Is this a typo that should be "NavigationBarLight"?

**Comment by fagundes** [comment]
Yes, it's a typo. Thank you. 

The same typo is in the code too.

**Comment by fagundes** [comment]
Fixed typo. Closing.

Feel free to reopen it if you need.
