### ISSUE TITLE
Support manually toggling SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR

### ISSUE THREAD

**Issue by dlee** [fagundes/cordova-plugin-navigationbar#4]
Right now, setting a navigationbar color always sets the button color to black. However, this makes darker navigationbar background colors unusable.

Can we make toggling SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR manual so that the dev can choose whether a darker or lighter button color fits their background color?

**Comment by ollm** [comment]
I have created a fork with a switch to activate and deactivate SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR

https://github.com/ollm/cordova-plugin-navigationbar

To install in cordova:

```
cordova plugin add https://github.com/ollm/cordova-plugin-navigationbar.git
```

A greeting

**Comment by fagundes** [comment]
I am merging the #5. Can I close this issue?

**Comment by dlee** [comment]
yes, thank you!
