### ISSUE TITLE
Not working on Android 9

### ISSUE THREAD

**Issue by Fever905** [fagundes/cordova-plugin-navigationbar#6]
This works perfectly on my Huawei Nexus 6P running Android 8.1.0.

However, this does not work on my Huawei P30 running  Android 9.  I am unable to change the color.  I am able to use the hide() function (from the ollu fork of this repo).

I went through a bunch of my apps on the Android 9 device and I see some of them are stuck using the default color, which on this device is light gray (very bright gray).  

Anyone else having this problem with Android 9?

Update: looks like this is intentional, apparently in Android 9 they dont want you changing the color because when they had it black it was burning in the screens of the Pixel 2 phones.  What a bunch of crap!!

**Comment by Fever905** [comment]
So technically this is not an issue, it's a limitation of the OS. You can close this.

**Comment by nikkozzblu** [comment]
This is not true, I see many apps having non standard color navigation bar (see Chees.com app for instance)

At the very least, we should be able to hide and fake it on android 9
