### ISSUE TITLE
NPM plugin not updated and intransparent releases

### ISSUE THREAD

**Issue by GoTo225** [fagundes/cordova-plugin-navigationbar#7]
Hi @fagundes,
first of all thank you for this amazing plugin!
During debugging I noticed, that you seemingly forgot to update the npm package associated with this repository. In addition, you have not created versions for your releases, which makes troubleshooting more difficult for you and the community.

**Comment by lucas-monteiro** [comment]
> Hi @fagundes,
> first of all thank you for this amazing plugin!
> During debugging I noticed, that you seemingly forgot to update the npm package associated with this repository. In addition, you have not created versions for your releases, which makes troubleshooting more difficult for you and the community.

Yes. I came in just to mention this update. I made a pull request that was accepted in github, but the npm is still outdated.

Can you upgrade to us?

Thank you once again for your time and contribution to the community.

**Comment by fagundes** [comment]
Thank you guys! I had updated! 
Sorry for the delay...

**Comment by lucas-monteiro** [comment]
> Thank you guys! I had updated!
> Sorry for the delay...

Obrigado!!!
